# overlays/staging/kustomization.yaml - staging environment overlay.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multistate-staging

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: multistate-dev
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-1"
  - target:
      kind: Deployment
      name: multistate-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: multistate-api-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: k8s,staging
      - op: replace
        path: /data/LOGGING_LEVEL_ROOT
        value: INFO
